### ISSUE TITLE
feat req: add a quit operation for better quitting

### ISSUE THREAD

**Issue by JerryWn12** [acheong08/ChatGPT-Proxy#12]

**Comment by fred913** [comment]
Please describe more detailedly - what does "quit operation" mean? A URL endpoint?

**Comment by JerryWn12** [comment]
press ctrl+c it should be quit normally but not some error message
```
INFO:     Shutting down
INFO:     Finished server process [4616]
Exception ignored in: <function Chrome.__del__ at 0x00000286FB53E200>
Traceback (most recent call last):
  File "C:\Users\JerryWn\.virtualenvs\ChatGPT-Proxy-qBbK2YsE\Lib\site-packages\undetected_chromedriver\__init__.py", line 788, in __del__
    self.quit()
  File "C:\Users\JerryWn\.virtualenvs\ChatGPT-Proxy-qBbK2YsE\Lib\site-packages\undetected_chromedriver\__init__.py", line 743, in quit
    time.sleep(0.1)
OSError: [WinError 6] 句柄无效。
```
