### ISSUE TITLE
Cloudflare token expired. Please wait a few minutes while I refresh

### ISSUE THREAD

**Issue by a0709** [acheong08/ChatGPT-Proxy#20]
Why do I keep reporting this error, I waited for a few minutes and it is still the same

**Comment by a0709** [comment]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:40593
from chrome not reachable

**Comment by a0709** [comment]
@fred913 @acheong08 Please give me a solution, thanks

**Comment by a0709** [comment]
Spawning browser...
Traceback (most recent call last):
  File "/app/proxy.py", line 33, in <module>
    ) = Cloudflare(proxy=GPT_PROXY).get_cf_cookies()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/OpenAIAuth/Cloudflare.py", line 81, in get_cf_cookies
    driver = uc.Chrome(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:52331
